kind: Service
apiVersion: v1
metadata:
  name: node-exporter-service
  namespace: traffic-operator-system
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9100"
spec:
  selector:
    app.kubernetes.io/component: traffic-operator-exporter
    app.kubernetes.io/name: traffic-operator-node-exporter
  type: NodePort
  ports:
    - name: traffic-operator-node-exporter
      protocol: TCP
      port: 9100
      targetPort: 9100
