apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9100"
    prometheus.io/scrape: "true"
  creationTimestamp: null
  name: traffic-operator-node-exporter-servie
spec:
  ports:
  - name: traffic-operator-node-exporter
    port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    app.kubernetes.io/component: traffic-operator-exporter
    app.kubernetes.io/name: traffic-operator-node-exporter
status:
  loadBalancer: {}
