apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "traffic.example.com/v1alpha1",
          "kind": "TrafficWatch",
          "metadata": {
            "name": "trafficwatch-sample"
          },
          "spec": {
            "deployment": {
              "replicas": 2,
              "selector": {
                "matchLabels": {
                  "app.kubernetes.io/component": "trafficwatch-sample",
                  "app.kubernetes.io/name": "trafficwatch-sample"
                }
              },
              "template": {
                "metadata": {
                  "labels": {
                    "app.kubernetes.io/component": "trafficwatch-sample",
                    "app.kubernetes.io/name": "trafficwatch-sample"
                  }
                },
                "spec": {
                  "containers": [
                    {
                      "command": [
                        "app"
                      ],
                      "image": "bash",
                      "name": "bash",
                      "resources": {
                        "limits": {
                          "cpu": "500m",
                          "memory": "128Mi"
                        },
                        "requests": {
                          "cpu": "10m",
                          "memory": "64Mi"
                        }
                      }
                    }
                  ]
                }
              }
            },
            "maxBandwidthPercent": "60"
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2025-01-01T15:55:14Z"
    operators.operatorframework.io/builder: operator-sdk-v1.38.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: traffic-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: TrafficWatch is the Schema for the trafficwatches API.
      displayName: Traffic Watch
      kind: TrafficWatch
      name: trafficwatches.traffic.example.com
      version: v1alpha1
  description: Operator managing node affinity of a deployment based on network traffic
    in each node
  displayName: traffic-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - list
          - watch
        - apiGroups:
          - apps
          resources:
          - daemonsets
          verbs:
          - create
        - apiGroups:
          - traffic.example.com
          resources:
          - trafficwatches
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - traffic.example.com
          resources:
          - trafficwatches/finalizers
          verbs:
          - update
        - apiGroups:
          - traffic.example.com
          resources:
          - trafficwatches/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: output-dir-controller-manager
      deployments:
      - label:
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: output-dir
          control-plane: controller-manager
        name: output-dir-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --metrics-bind-address=:8443
                - --leader-elect
                - --health-probe-bind-address=:8081
                command:
                - /manager
                image: pkopel/traffic-operator:v0.0.1
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: output-dir-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: output-dir-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - traffic
  - affinity
  - node
  links:
  - name: Traffic Operator
    url: https://traffic-operator.domain
  maintainers:
  - email: pawel.kopel2@gmail.com
    name: PKopel
  maturity: alpha
  provider:
    name: PKopel
    url: https://github.com/PKopel
  version: 0.0.1
