apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: traffic-operator-trafficwatch-viewer-role
rules:
- apiGroups:
  - traffic.example.com
  resources:
  - trafficwatches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - traffic.example.com
  resources:
  - trafficwatches/status
  verbs:
  - get
