apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: traffic-operator-catalog
  namespace: olm
spec:
  sourceType: grpc
  image: pkopel/traffic-operator-catalog:v0.0.1
  displayName: Traffic Operator Catalog
  publisher: PKopel
  updateStrategy:
    registryPoll:
      interval: 30m
