---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - traffic.example.com
  resources:
  - trafficwatches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - traffic.example.com
  resources:
  - trafficwatches/finalizers
  verbs:
  - update
- apiGroups:
  - traffic.example.com
  resources:
  - trafficwatches/status
  verbs:
  - get
  - patch
  - update
