# permissions for end users to view trafficwatches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trafficwatch-viewer-role
rules:
  - apiGroups:
      - traffic.example.com
    resources:
      - trafficwatches
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - traffic.example.com
    resources:
      - trafficwatches/status
    verbs:
      - get
