name: Lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
